# Generated by Django 5.2.8 on 2025-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alianzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alianza',
            name='correo_electronico',
            field=models.EmailField(
                max_length=254,
                unique=True,
                null=True,
                blank=True,
                default=None,
            ),
        ),
    ]
