# Generated by Django 5.2.8 on 2025-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alianzas', '0003_alter_alianza_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alianza',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
