# Generated by Django 5.2.8 on 2025-11-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0003_remove_dispersion_total_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='facturadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='servicio',
            field=models.CharField(default='MORWELL', max_length=50),
            preserve_default=False,
        ),
    ]
