# Generated by Django 5.2.8 on 2026-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0010_dispersion_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('PPD', 'PPD'), ('PUE', 'PUE')], max_length=100, null=True),
        ),
    ]
