# Generated by Django 5.2.8 on 2026-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0011_alter_dispersion_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersion',
            name='monto_bloqueado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
