# Generated by Django 5.2.8 on 2026-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0013_remove_dispersion_monto_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='monto_dispersion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
