# Generated by Django 5.2.8 on 2025-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_comision1_alter_cliente_comision10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(choices=[('PROCOM', 'PROCOM'), ('MUTUALINK', 'Mutualink'), ('PRESTAMO', 'Préstamo'), ('PRAIDS', 'PRAIDS'), ('MONEDEROS', 'Monederos'), ('HIDROCARBUROS', 'Hidrocarburos'), ('VP360', 'VP360')], max_length=20),
        ),
    ]
