# Generated by Django 5.2.8 on 2025-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(choices=[('PROCOM', 'PROCOM'), ('MUTUALINK', 'Mutualink'), ('PRESTAMO', 'Prestamo'), ('PRAIDS', 'PRAIDS'), ('MONEDEROS', 'Monederos'), ('HIDROCARBUROS', 'Hidrocarburos'), ('VP360', 'VP360')], max_length=20),
        ),
    ]
