# Generated by Django 5.2.8 on 2026-01-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alianzas", "0004_alter_alianza_correo_electronico"),
        ("clientes", "0009_cliente_comision11_cliente_comisionista11"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="comision12",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="comisionista12",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_comisionista12",
                to="alianzas.alianza",
            ),
        ),
    ]
