# Generated by Django 5.2.8 on 2026-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_comision12_cliente_comisionista12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Otros', 'Otros'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Hidrocarburos', 'Hidrocarburos'), ('Marketing', 'Marketing'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('STEE', 'STEE'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Reclutamiento', 'Reclutamiento')], max_length=50),
        ),
    ]
