# Generated by Django 5.2.8 on 2026-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_merge_0012_facturadora_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ac',
            field=models.CharField(blank=True, choices=[('CONFEDIN', 'CONFEDIN'), ('CAMARENCE', 'CAMARENCE'), ('HATRES', 'HATRES'), ('SERVIARUGA', 'SERVIARUGA'), ('ZAMORA', 'ZAMORA'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('PPD', 'PPD'), ('PUE', 'PUE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Otros', 'Otros'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Hidrocarburos', 'Hidrocarburos'), ('Laboral', 'Laboral'), ('Marketing', 'Marketing'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('STEE', 'STEE'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Reclutamiento', 'Reclutamiento')], max_length=50),
        ),
    ]
