# Generated by Codex on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispersiones_servicios", "0011_alter_dispersion_forma_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispersion",
            name="num_factura",
        ),
        migrations.RemoveField(
            model_name="dispersion",
            name="num_factura_honorarios",
        ),
        migrations.RemoveField(
            model_name="dispersion",
            name="estatus_proceso",
        ),
        migrations.RemoveField(
            model_name="dispersion",
            name="num_periodo",
        ),
        migrations.RemoveField(
            model_name="dispersion",
            name="estatus_periodo",
        ),
    ]
