# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispersiones_servicios", "0012_remove_campos_dispersion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispersion",
            name="cliente",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="dispersiones_servicios",
                related_query_name="dispersiones_servicios",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="dispersion",
            name="ejecutivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="dispersiones_servicios_ejecutivo",
                to="auth.user",
            ),
        ),
    ]
