# Generated by Django 5.2.8 on 2026-02-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones_servicios', '0014_remove_dispersion_factura_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersion',
            name='factura_solicitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispersion',
            name='monto_bloqueado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
