# Generated by Django 5.2.8 on 2026-02-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones_servicios', '0015_dispersion_factura_solicitada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispersion',
            name='monto_bloqueado',
        ),
    ]
