# Generated by Django 5.2.8 on 2026-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones_servicios', '0016_remove_dispersion_monto_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersion',
            name='num_factura_honorarios',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
