# Generated by Codex on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0002_comision_servicio"),
        ("comisiones", "0002_pagocomision"),
    ]

    operations = []
